Add support for MySQL Coordinator
kubedb/mysql pull request #406
Opened 2021-09-21 14:34 UTC by heheh13

2021-09-29 11:55 UTC, spectro30 requested changes

2021-09-29 11:55 UTC, spectro30 commented on pkg/controller/rbac.go
>  func (c *Controller) ensureDatabaseRBAC(db *api.MySQL) error {
take a look into the whole function

2021-09-29 11:55 UTC, spectro30 commented on pkg/controller/router.go
> +		Name:      "router-config",
use constant

2021-09-29 11:55 UTC, spectro30 commented on pkg/controller/rbac.go
> +		db.Spec.PodTemplate.Spec.ServiceAccountName = db.OffshootName()
recheck the access

2021-09-29 11:55 UTC, spectro30 commented on pkg/controller/rbac.go
>  	}
create new sa for router

2021-09-29 11:55 UTC, spectro30 commented on pkg/controller/service.go
> +				"Successfully created service for Innodb Cluster ",
Successfully created service for `router name`

2021-09-29 11:55 UTC, spectro30 commented on pkg/controller/service.go
> +						//TargetPort: intstr.FromString(api.MySQLDatabasePortName),
check if it produce any unwanted logs in operator

2021-09-29 11:55 UTC, spectro30 commented on pkg/controller/service.go
> +		in.Annotations = svcTemplate.Annotations
did the same thing on line 223

2021-09-29 11:55 UTC, spectro30 commented on pkg/controller/health.go
> +// health checker algorithm
remove commented codes

2021-09-29 11:55 UTC, spectro30 commented on pkg/controller/health.go
> +			err = c.updateMySQLStatusConditions(ctx, db, kmapi.Condition{
maybe add this function in api machinery if it's not already there!

2021-09-29 11:55 UTC, spectro30 commented on pkg/controller/health.go
> +				err := c.updateMySQLStatusConditions(ctx, db, kmapi.Condition{
maybe add this function in api machinery if it's not already there!

2021-09-29 11:55 UTC, spectro30 commented on pkg/controller/health.go
> +		serverSecret, err := c.Client.CoreV1().Secrets(db.Namespace).Get(ctx, db.MustCertSecretName(api.MySQLClientCert), metav1.GetOptions{})
shouldn't we use MySQLServerCert?

2021-10-07 13:12 UTC, heheh13 commented on pkg/controller/router.go
> +const (
will try next .

2021-11-02 07:43 UTC, merged