Add Support for MySQL Read Replica
kubedb/mysql pull request #439
Opened 2021-12-02 16:00 UTC by heheh13

Signed-off-by: Mehedi Hasan <mehedi.hasan@appscode.com>

2022-02-14 09:59 UTC, spectro30 requested changes

2022-02-14 09:59 UTC, spectro30 commented on pkg/controller/router.go
> +	////router will be created after the server is ready
remove commented codes

2022-02-14 09:59 UTC, spectro30 commented on pkg/controller/env.go
> +		sourceObj, err := c.DBClient.KubedbV1alpha2().MySQLs(sourceNameSpace).Get(context.TODO(), sourceName, metav1.GetOptions{})
handle error or hardcode

2022-02-14 09:59 UTC, spectro30 commented on pkg/controller/statefulset.go
> +	dbObj, err := c.DBClient.KubedbV1alpha2().MySQLs(sourceNameSpace).Get(context.TODO(), sourceName, metav1.GetOptions{})
get dbObj before CreateOrPatchStatefulSet call

2022-02-14 09:59 UTC, spectro30 commented on pkg/controller/statefulset.go
>  func upsertUserEnv(statefulSet *apps.StatefulSet, db *api.MySQL) *apps.StatefulSet {
Move this function to env.go file?

2022-02-14 09:59 UTC, spectro30 commented on pkg/controller/statefulset.go
> +			if db.IsReadReplica() && c.SourceHasSSL(db) {
move this block to `upsertTLSVolume`? Since this volume is TLS related.

2022-02-14 09:59 UTC, spectro30 commented on pkg/controller/statefulset.go
> +			if db.IsReadReplica() && c.SourceHasSSL(db) {
**what will happen when add/remove tls opsReq is performed in sourceDB?**

2022-02-15 07:06 UTC, heheh13 commented on pkg/admission/validator.go
> -		if *mysql.Spec.Topology.Mode == api.MySQLClusterModeGroupReplication {
added.

2022-02-15 07:13 UTC, heheh13 commented on pkg/controller/secret.go
> +	sec, err := c.Client.CoreV1().Secrets(db.Namespace).Get(context.TODO(), db.GetAuthSecretName(), metav1.GetOptions{})
checking for exisinting secret
if not present it will create new one from source db auth

2022-02-15 07:17 UTC, heheh13 commented on pkg/controller/secret.go
> +func (c *Reconciler) isInAllowedNamespaces(requestedDB *api.MySQL, referredDB *api.MySQL) (bool, error) {
updated.

2022-02-15 08:47 UTC, heheh13 commented on pkg/controller/secret.go
> +func (c *Reconciler) isMatchByLabels(requestedDB *api.MySQL, referredDB *api.MySQL) (bool, error) {
updated.

2022-02-17 09:42 UTC, heheh13 commented on pkg/controller/statefulset.go
> +			if db.IsReadReplica() && c.SourceHasSSL(db) {
need to restart the read replica .
we are planning to do a restart the the replica from ops request.

2022-02-17 17:10 UTC, faem requested changes

2022-02-17 17:10 UTC, faem commented on pkg/admission/validator.go
> +	return true, nil
I think the right way to match selector is `selector.Matches(labels.Set(labels))`

2022-02-17 17:10 UTC, faem commented on pkg/admission/validator.go
> +					}
I think the right way to match selector is `selector.Matches(labels.Set(labels))`

2022-02-18 06:10 UTC, heheh13 commented on pkg/controller/statefulset.go
> +		//args = append(args, "--datadir=/var/lib/mysql/data")
i thing we need that
remove commemnt

2022-02-18 07:54 UTC, heheh13 commented on pkg/admission/validator.go
> +	return true, nil
updated some. 
will try to update later.

2022-02-18 09:20 UTC, faem submitted a review, later dismissed
LGTM

2022-02-18 09:29 UTC, spectro30 approved these changes
LGTM

2022-02-18 09:38 UTC, merged