Add Support for Semi-sync cluster
kubedb/mysql pull request #464
Opened 2022-04-20 05:48 UTC by heheh13

2022-04-28 09:18 UTC, spectro30 requested changes

2022-04-28 09:18 UTC, spectro30 commented on pkg/controller/statefulset.go
> +	//if db.UsesGroupReplication() {
remove commented code

2022-04-28 09:18 UTC, spectro30 commented on pkg/controller/statefulset.go
> +		if db.Spec.Topology.SemiSync != nil {
add nil check for `SemiSyncMasterTimeout` and `SemiSyncMasterWaitFoSlaveCount`

2022-05-11 09:24 UTC, heheh13 commented on pkg/controller/health.go
> +	// ready, critical , not ready..
random comments while coding.
removed

2022-05-12 09:36 UTC, heheh13 commented on pkg/controller/health.go
> +		kmapi.Condition{
udpated

2022-05-16 07:51 UTC, heheh13 commented on pkg/controller/health.go
>  				dns := HostDNS(db, pod.ObjectMeta)
I think it will be better to rework in the next release.

2022-05-17 05:26 UTC, spectro30 approved these changes
LGTM

2022-05-17 08:48 UTC, merged